# Generated by Django 3.0.8 on 2020-08-27 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_todo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='field',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
