# Generated by Django 3.0.6 on 2020-08-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200828_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tasked',
        ),
    ]
