# Generated by Django 3.0.6 on 2020-08-29 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_todo_tasked'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='tasked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
